# Test Benchmark — Mini protocole

Protocole réduit pour valider le pipeline avant le benchmark complet.

| Paramètre | Valeur |
|---|---|
| Images profiling | 30 (640×640) |
| Images MAP | 10 (résolution originale) |
| Warmup | 5 itérations |
| Mesure | 10 itérations |
| Seed | 42 |

**Deux modes distincts :**
- **Profiling** → `load_model()` + `preprocess()` : images 640×640, comparaison de vitesse standardisée
- **MAP eval** → `load_model_eval()` + `evaluate_map()` : résolution native du modèle, conforme COCO

## 1. Configuration

In [1]:
import sys, os
sys.path.insert(0, os.path.abspath("."))

import torch
import numpy as np
import pandas as pd
from pathlib import Path

IMG_DIR     = "datasets/coco/val2017"
ANN_FILE    = "datasets/coco/annotations/instances_val2017.json"
RESULTS_DIR = Path("results")
RESULTS_DIR.mkdir(exist_ok=True)

N_PROFILE_IMAGES = 300
N_EVAL_IMAGES    = 10
N_WARMUP         = 5
N_MEASURE        = 10
SEED             = 42
DEVICE           = "cuda" if torch.cuda.is_available() else "cpu"

print(f"Device : {DEVICE}")
if DEVICE == "cuda":
    print(f"GPU    : {torch.cuda.get_device_name(0)}")
    print(f"VRAM   : {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

Device : cuda
GPU    : NVIDIA GeForce RTX 5060 Laptop GPU
VRAM   : 8.5 GB

## 2. Chargement des données

- `load_profiling_data` → images redimensionnées à 640×640
- `load_eval_data` → images à résolution originale COCO (variable)

In [2]:
from utils.data_loader import load_profiling_data, load_eval_data

profile_data        = load_profiling_data(IMG_DIR, ANN_FILE, n=N_PROFILE_IMAGES, seed=SEED)
eval_data, coco_gt  = load_eval_data(IMG_DIR, ANN_FILE, n=N_EVAL_IMAGES, seed=SEED)

print(profile_data)           # LazySampleList(n=30, ...)
print(f"Premier sample profiling : {profile_data[0]}")
print(f"Premier sample eval      : {eval_data[0]}")

loading annotations into memory...
Done (t=0.52s)
creating index...
index created!
loading annotations into memory...
Done (t=0.54s)
creating index...
index created!
LazySampleList(n=300, img_dir='datasets/coco/val2017')
Premier sample profiling : {'image_id': 107554, 'path': 'datasets\\coco\\val2017\\000000107554.jpg', 'orig_size': (480, 640)}
Premier sample eval      : {'image_id': 107554, 'path': 'datasets\\coco\\val2017\\000000107554.jpg', 'orig_size': (480, 640)}

## 3. Fonctions utilitaires

In [3]:
from utils.benchmark import benchmark_model, ModuleBenchmark

# Accumulateurs pour les CSV finaux
profiling_rows, map_rows = [], []

def record(name, result, maps):
    profiling_rows.append({"model": name, **{k: v for k, v in result.items() if k != "modules"}})
    map_rows.append({"model": name, **maps})
    print(f"  Benchmark (640×640) : {result['mean_ms']:.1f} ms ± {result['std_ms']:.1f}  ({result['fps']:.1f} FPS)")
    print(f"  MAP (native res)    : AP={maps.get('AP', -1):.3f}  AP50={maps.get('AP50', -1):.3f}")

print("OK — benchmark_model, ModuleBenchmark importés depuis utils/benchmark.py")

OK — benchmark_model, ModuleBenchmark importés depuis utils/benchmark.py

## 4. RetinaNet R50

In [4]:
import models.retinanet_r50 as r50

print("Chargement modèle benchmark...")
model_r50  = r50.load_model(DEVICE)
result_r50 = benchmark_model(model_r50, profile_data, r50.preprocess, r50.collate,
                             n_warmup=N_WARMUP, n_measure=N_MEASURE, device=DEVICE)
del model_r50; torch.cuda.empty_cache()

print("Chargement eval model + MAP...")
model_r50_eval = r50.load_model_eval(DEVICE)
map_r50        = r50.evaluate_map(model_r50_eval, eval_data, coco_gt, DEVICE)
del model_r50_eval; torch.cuda.empty_cache()

record("retinanet_r50", result_r50, map_r50)

Chargement modèle benchmark...
Chargement eval model + MAP...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.14s).
Accumulating evaluation results...
DONE (t=0.09s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.525
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.820
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.535
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.305
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.546
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.728
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.428
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.537
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.573
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.307
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.622
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.768
  Benchmark (640×640) : 66.9 ms ± 6.0  (15.0 FPS)
  MAP (native res)    : AP=0.525  AP50=0.820

## 5. RetinaNet R101

In [5]:
import models.retinanet_r101 as r101

print("Chargement modèle benchmark...")
model_r101  = r101.load_model(DEVICE)
result_r101 = benchmark_model(model_r101, profile_data, r101.preprocess, r101.collate,
                              n_warmup=N_WARMUP, n_measure=N_MEASURE, device=DEVICE)
del model_r101; torch.cuda.empty_cache()

print("Chargement eval model + MAP...")
model_r101_eval = r101.load_model_eval(DEVICE)
map_r101        = r101.evaluate_map(model_r101_eval, eval_data, coco_gt, DEVICE)
del model_r101_eval; torch.cuda.empty_cache()

record("retinanet_r101", result_r101, map_r101)

Loading config d:\school\ProjectDSAI2026_2\detectron2\model_zoo\configs\COCO-Detection\../Base-RetinaNet.yaml with yaml.unsafe_load. Your machine may be at risk if the file contains malicious content.

Chargement modèle benchmark...

The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std
c:\ProgramData\anaconda3\Lib\site-packages\torch\functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:4324.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Loading config d:\school\ProjectDSAI2026_2\detectron2\model_zoo\configs\COCO-Detection\../Base-RetinaNet.yaml with yaml.unsafe_load. Your machine may be at risk if the file contains malicious content.

Chargement eval model + MAP...

The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std

Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.07s).
Accumulating evaluation results...
DONE (t=0.07s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.474
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.708
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.494
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.203
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.520
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.708
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.371
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.519
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.573
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.265
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.623
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.736
  Benchmark (640×640) : 76.2 ms ± 6.1  (13.1 FPS)
  MAP (native res)    : AP=0.474  AP50=0.708

## 6. FCOS R50

In [6]:
import models.fcos_r50 as fcos

print("Chargement modèle benchmark...")
model_fcos  = fcos.load_model(DEVICE)
result_fcos = benchmark_model(model_fcos, profile_data, fcos.preprocess, fcos.collate,
                              n_warmup=N_WARMUP, n_measure=N_MEASURE, device=DEVICE)
del model_fcos; torch.cuda.empty_cache()

print("Chargement eval model + MAP...")
model_fcos_eval = fcos.load_model_eval(DEVICE)
map_fcos        = fcos.evaluate_map(model_fcos_eval, eval_data, coco_gt, DEVICE)
del model_fcos_eval; torch.cuda.empty_cache()

record("fcos_r50", result_fcos, map_fcos)

Chargement modèle benchmark...
Chargement eval model + MAP...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.08s).
Accumulating evaluation results...
DONE (t=0.07s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.514
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.764
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.580
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.366
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.533
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.674
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.389
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.541
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.569
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.379
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.601
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.761
  Benchmark (640×640) : 64.1 ms ± 14.8  (15.6 FPS)
  MAP (native res)    : AP=0.514  AP50=0.764

## 7. EfficientDet — test pipeline (PIL + F.normalize, sans +1)

In [7]:
# ── Test rapide D4 avec le pipeline PIL copié de l'ancien code ──────────────────
import importlib
import models.efficientdet_d4 as ed4
importlib.reload(ed4)

print("Chargement D4 eval model...")
model_ed4_test = ed4.load_model_eval(DEVICE)

print(f"Évaluation MAP sur {N_EVAL_IMAGES} images...")
map_ed4_test = ed4.evaluate_map(model_ed4_test, eval_data, coco_gt, DEVICE)
del model_ed4_test; torch.cuda.empty_cache()

print(f"\n>>> D4 AP  = {map_ed4_test['AP']:.4f}  (attendu ~0.43)")
print(f">>> D4 AP50= {map_ed4_test['AP50']:.4f}  (attendu ~0.62)")
print(f"\nRésultat complet : {map_ed4_test}")

Chargement D4 eval model...
Évaluation MAP sur 10 images...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.07s).
Accumulating evaluation results...
DONE (t=0.06s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.582
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.738
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.633
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.362
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.593
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.879
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.459
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.618
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.648
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.421
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.608
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.896

>>> D4 AP  = 0.5817  (attendu ~0.43)
>>> D4 AP50= 0.7383  (attendu ~0.62)

Résultat complet : {'AP': 0.5817148031511211, 'AP50': 0.7383492874174296, 'AP75': 0.6334692292758687, 'APs': 0.3616336633663366, 'APm': 0.5927392739273927, 'APl': 0.8789250353606789}

In [8]:
import models.efficientdet_d4 as ed4

print("Chargement modèle benchmark...")
model_ed4  = ed4.load_model(DEVICE)
result_ed4 = benchmark_model(model_ed4, profile_data, ed4.preprocess, ed4.collate,
                             n_warmup=N_WARMUP, n_measure=N_MEASURE, device=DEVICE)
del model_ed4; torch.cuda.empty_cache()

print("Chargement eval model + MAP...")
model_ed4_eval = ed4.load_model_eval(DEVICE)
map_ed4        = ed4.evaluate_map(model_ed4_eval, eval_data, coco_gt, DEVICE)
del model_ed4_eval; torch.cuda.empty_cache()

record("efficientdet_d4", result_ed4, map_ed4)

Chargement modèle benchmark...
Chargement eval model + MAP...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.06s).
Accumulating evaluation results...
DONE (t=0.07s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.582
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.738
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.633
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.362
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.593
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.879
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.459
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.618
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.648
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.421
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.608
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.896
  Benchmark (640×640) : 60.9 ms ± 5.9  (16.4 FPS)
  MAP (native res)    : AP=0.582  AP50=0.738

## 8. EfficientDet D5

In [9]:
import models.efficientdet_d5 as ed5

print("Chargement modèle benchmark...")
model_ed5  = ed5.load_model(DEVICE)
result_ed5 = benchmark_model(model_ed5, profile_data, ed5.preprocess, ed5.collate,
                             n_warmup=N_WARMUP, n_measure=N_MEASURE, device=DEVICE)
del model_ed5; torch.cuda.empty_cache()

print("Chargement eval model + MAP...")
model_ed5_eval = ed5.load_model_eval(DEVICE)
map_ed5        = ed5.evaluate_map(model_ed5_eval, eval_data, coco_gt, DEVICE)
del model_ed5_eval; torch.cuda.empty_cache()

record("efficientdet_d5", result_ed5, map_ed5)

Chargement modèle benchmark...
Chargement eval model + MAP...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.05s).
Accumulating evaluation results...
DONE (t=0.07s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.524
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.728
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.605
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.417
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.573
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.764
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.415
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.555
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.587
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.428
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.583
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.829
  Benchmark (640×640) : 71.5 ms ± 10.9  (14.0 FPS)
  MAP (native res)    : AP=0.524  AP50=0.728

## 9. EfficientDet D6

In [10]:
import models.efficientdet_d6 as ed6

print("Chargement modèle benchmark...")
model_ed6  = ed6.load_model(DEVICE)
result_ed6 = benchmark_model(model_ed6, profile_data, ed6.preprocess, ed6.collate,
                             n_warmup=N_WARMUP, n_measure=N_MEASURE, device=DEVICE)
del model_ed6; torch.cuda.empty_cache()

print("Chargement eval model + MAP...")
model_ed6_eval = ed6.load_model_eval(DEVICE)
map_ed6        = ed6.evaluate_map(model_ed6_eval, eval_data, coco_gt, DEVICE)
del model_ed6_eval; torch.cuda.empty_cache()

record("efficientdet_d6", result_ed6, map_ed6)

Chargement modèle benchmark...
Chargement eval model + MAP...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.07s).
Accumulating evaluation results...
DONE (t=0.08s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.507
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.692
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.532
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.295
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.561
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.760
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.374
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.584
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.620
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.356
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.589
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.893
  Benchmark (640×640) : 83.2 ms ± 12.7  (12.0 FPS)
  MAP (native res)    : AP=0.507  AP50=0.692

## 10. Résultats

In [11]:
df_prof = pd.DataFrame(profiling_rows).set_index("model")
df_map  = pd.DataFrame(map_rows).set_index("model")

df_prof.to_csv(RESULTS_DIR / "profiling_test.csv")
df_map.to_csv(RESULTS_DIR  / "map_test.csv")

print("=== Profiling — 640×640 (ms) ===")
display(df_prof.round(2))

print("\n=== MAP — résolution native COCO ===")
display(df_map.round(3))

print(f"\nCSV sauvegardés dans {RESULTS_DIR.resolve()}")

=== Profiling — 640×640 (ms) ===

                 mean_ms  std_ms  min_ms  max_ms    fps
model
retinanet_r50      66.86    6.04   59.71   78.27  14.96
retinanet_r101     76.16    6.12   69.45   89.49  13.13
fcos_r50           64.07   14.82   55.72  107.38  15.61
efficientdet_d4    60.87    5.93   52.75   72.16  16.43
efficientdet_d5    71.45   10.91   60.70   93.84  13.99
efficientdet_d6    83.24   12.66   78.26  121.15  12.01

=== MAP — résolution native COCO ===

                    AP   AP50   AP75    APs    APm    APl
model
retinanet_r50    0.525  0.820  0.535  0.305  0.546  0.728
retinanet_r101   0.474  0.708  0.494  0.203  0.520  0.708
fcos_r50         0.514  0.764  0.580  0.366  0.533  0.674
efficientdet_d4  0.582  0.738  0.633  0.362  0.593  0.879
efficientdet_d5  0.524  0.728  0.605  0.417  0.573  0.764
efficientdet_d6  0.507  0.692  0.532  0.295  0.561  0.760

CSV sauvegardés dans D:\school\ProjectDSAI2026_2\results

## 11. Profilage méso-scopique — PyTorch Profiler

Décomposition du forward pass par opération PyTorch (couche par couche).

Le profiler utilise son propre `schedule(wait=0, warmup=N_WARMUP, active=N_MEASURE)` :
- phase warmup : GPU chauffe, trace collectée mais non commitée
- phase active : trace exportée vers TensorBoard + Chrome JSON

**Sorties :**
```
results/profiler/pytorch/<model>/
  tensorboard/        ← tensorboard --logdir results/profiler/pytorch/<model>/tensorboard
  chrome_trace.json   ← chrome://tracing  ou  ui.perfetto.dev
  summary*.txt        ← tableaux triés par cuda_time_total
```

In [ ]:
from profiler.pytorch_profiler import profile_with_pytorch

PROF_OUTPUT  = "results/profiler/pytorch"
PROFILER_TAG = "baseline"

MODELS_TO_PROFILE = {
    "retinanet_r50":   (r50,  r50.load_model),
    "retinanet_r101":  (r101, r101.load_model),
    "fcos_r50":        (fcos, fcos.load_model),
    "efficientdet_d4": (ed4,  ed4.load_model),
    "efficientdet_d5": (ed5,  ed5.load_model),
    "efficientdet_d6": (ed6,  ed6.load_model),
}

pytorch_prof_results = {}

for model_name, (mod, load_fn) in MODELS_TO_PROFILE.items():
    print(f"\n{'─'*55}")
    print(f"  {model_name}  [tag={PROFILER_TAG}]")
    print(f"{'─'*55}")

    model = load_fn(DEVICE)
    result = profile_with_pytorch(
        model=model, data=profile_data,
        preprocess_fn=mod.preprocess, collate_fn=mod.collate,
        n_warmup=N_WARMUP, n_active=N_MEASURE,
        output_dir=PROF_OUTPUT, model_name=model_name,
        tag=PROFILER_TAG, device=DEVICE,
    )
    result["profiler"].export_chrome_trace(f"{PROF_OUTPUT}/{result['run_name']}/tensorboard/{result['run_name']}.pt.trace.json")
    pytorch_prof_results[model_name] = result
    del model; torch.cuda.empty_cache()

print(f"\nTraces dans : {PROF_OUTPUT}")
print(f"Ouvrir dans chrome://tracing ou ui.perfetto.dev")

───────────────────────────────────────────────────────
  retinanet_r50  [tag=baseline]
───────────────────────────────────────────────────────

==============================================================
  PyTorch Profiler — retinanet_r50__baseline__20260613_184058
==============================================================
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg       CPU Mem  Self CPU Mem    # of Calls  Total KFLOPs
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                          ProfilerStep*        18.45%     210.041ms       100.00%        1.139s     113.866ms           0 B           0 B            10            --
                                       aten::lift_fresh         0.01%     142.000us         0.01%     142.000us       0.789us           0 B           0 B           180            --
                                          aten::permute         0.19%       2.190ms         0.22%       2.550ms      23.185us           0 B           0 B           110            --
                                       aten::as_strided         0.41%       4.686ms         0.41%       4.686ms       1.391us           0 B           0 B          3370            --
                                               aten::to         0.13%       1.485ms         2.86%      32.610ms      63.942us          40 B           0 B           510            --
                                         aten::_to_copy         0.33%       3.755ms         2.73%      31.126ms     155.629us          40 B           0 B           200            --
                                    aten::empty_strided         0.29%       3.312ms         0.29%       3.312ms      16.562us          40 B          40 B           200            --
                                            aten::copy_         0.70%       7.945ms         3.08%      35.055ms      76.207us           0 B         -40 B           460            --
                                        cudaMemcpyAsync         1.87%      21.304ms         1.87%      21.304ms      64.559us           0 B           0 B           330            --
                                  cudaStreamSynchronize         4.56%      51.903ms         4.56%      51.903ms     178.975us           0 B           0 B           290            --
                                          model_forward        25.54%     290.807ms        80.09%     912.003ms      91.200ms           0 B        -880 B            10            --
                                            aten::empty         2.69%      30.638ms         2.69%      30.638ms       6.437us         880 B         880 B          4760            --
                                            aten::slice         0.92%      10.465ms         1.06%      12.054ms      10.573us           0 B           0 B          1140            --
                                        aten::unsqueeze         0.62%       7.013ms         0.70%       7.971ms       8.857us           0 B           0 B           900            --
                                              aten::sub         0.39%       4.462ms         0.71%       8.076ms      38.455us           0 B           0 B           210            --
                                       cudaLaunchKernel        12.20%     138.931ms        12.20%     138.931ms      15.593us           0 B           0 B          8910            --
                                              aten::div         0.55%       6.265ms         0.99%      11.328ms      40.458us           0 B           0 B           280            --
                              aten::upsample_bilinear2d         0.07%     844.200us         0.15%       1.675ms     167.490us           0 B           0 B            10            --
                                           aten::select         0.42%       4.763ms         0.49%       5.564ms       9.761us           0 B           0 B           570            --
                                         aten::new_full         0.02%     186.400us         0.09%       1.069ms     106.890us           0 B           0 B            10            --
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 1.139s


  Run         : retinanet_r50__baseline__20260613_184058
  Perfetto    : glisser le fichier sur ui.perfetto.dev
  Chrome      : ouvrir chrome://tracing → Load → sélectionner le fichier
  TensorBoard : tensorboard --logdir results\profiler\pytorch\retinanet_r50__baseline__20260613_184058\tensorboard
  Résumés     : results\profiler\pytorch\retinanet_r50__baseline__20260613_184058/summary*.txt

WARNING:fvcore.common.config:Loading config d:\school\ProjectDSAI2026_2\detectron2\model_zoo\configs\COCO-Detection\../Base-RetinaNet.yaml with yaml.unsafe_load. Your machine may be at risk if the file contains malicious content.

───────────────────────────────────────────────────────
  retinanet_r101  [tag=baseline]
───────────────────────────────────────────────────────

WARNING:fvcore.common.checkpoint:The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std

==============================================================
  PyTorch Profiler — retinanet_r101__baseline__20260613_184113
==============================================================
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg       CPU Mem  Self CPU Mem    # of Calls  Total KFLOPs
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                          ProfilerStep*         8.83%      77.694ms       100.00%     879.563ms      87.956ms           0 B           0 B            10            --
                                       aten::lift_fresh         0.01%      48.100us         0.01%      48.100us       1.603us           0 B           0 B            30            --
                                          aten::permute         0.07%     574.100us         0.08%     713.300us       6.485us           0 B           0 B           110            --
                                       aten::as_strided         0.30%       2.638ms         0.30%       2.638ms       0.788us           0 B           0 B          3350            --
                                               aten::to         0.09%     814.300us        27.55%     242.296ms     438.942us          40 B           0 B           552            --
                                         aten::_to_copy         0.22%       1.903ms        27.45%     241.482ms       1.725ms          40 B           0 B           140            --
                                    aten::empty_strided         0.17%       1.496ms         0.17%       1.496ms       9.975us          40 B          40 B           150            --
                                            aten::copy_         0.46%       4.060ms        27.86%     245.012ms     583.363us           0 B         -40 B           420            --
                                        cudaMemcpyAsync         1.71%      15.061ms         1.71%      15.061ms      48.584us           0 B           0 B           310            --
                                  cudaStreamSynchronize        26.68%     234.651ms        26.68%     234.651ms     869.079us           0 B           0 B           270            --
                                          model_forward        21.29%     187.234ms        89.91%     790.772ms      79.077ms           0 B     -13.44 KB            10            --
                                              aten::sub         0.38%       3.363ms         0.69%       6.087ms      24.349us         160 B         160 B           250            --
                                       cudaLaunchKernel         9.51%      83.621ms         9.51%      83.621ms       8.382us           0 B           0 B          9976            --
                                              aten::div         0.29%       2.521ms         0.50%       4.423ms      20.105us         160 B         160 B           220            --
                                            aten::empty         1.74%      15.264ms         1.74%      15.264ms       3.347us         240 B         240 B          4560            --
                                            aten::stack         0.21%       1.812ms         0.80%       7.036ms      58.632us         160 B           0 B           120            --
                                              aten::cat         0.32%       2.788ms         0.57%       4.993ms      33.285us         160 B         160 B           150            --
                                             aten::view         0.43%       3.821ms         0.43%       3.821ms       1.679us           0 B           0 B          2276            --
                                              aten::max         0.20%       1.788ms         0.28%       2.425ms     121.250us         320 B         320 B            20            --
                                       aten::unsqueeze_         0.02%     167.200us         0.03%     256.500us       8.550us           0 B           0 B            30            --
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 879.563ms


  Run         : retinanet_r101__baseline__20260613_184113
  Perfetto    : glisser le fichier sur ui.perfetto.dev
  Chrome      : ouvrir chrome://tracing → Load → sélectionner le fichier
  TensorBoard : tensorboard --logdir results\profiler\pytorch\retinanet_r101__baseline__20260613_184113\tensorboard
  Résumés     : results\profiler\pytorch\retinanet_r101__baseline__20260613_184113/summary*.txt

───────────────────────────────────────────────────────
  fcos_r50  [tag=baseline]
───────────────────────────────────────────────────────

==============================================================
  PyTorch Profiler — fcos_r50__baseline__20260613_184128
==============================================================
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg       CPU Mem  Self CPU Mem    # of Calls  Total MFLOPs
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                          ProfilerStep*         9.20%     105.930ms       100.00%        1.152s     115.164ms           0 B           0 B            10            --
                                       aten::lift_fresh         0.01%     116.100us         0.01%     116.100us       1.451us           0 B           0 B            80            --
                                          aten::permute         0.16%       1.880ms         0.20%       2.329ms      14.554us           0 B           0 B           160            --
                                       aten::as_strided         0.30%       3.492ms         0.30%       3.492ms       1.284us           0 B           0 B          2720            --
                                               aten::to         0.09%       1.046ms         2.21%      25.426ms      82.021us          40 B           0 B           310            --
                                         aten::_to_copy         0.20%       2.329ms         2.12%      24.381ms     243.807us          40 B           0 B           100            --
                                    aten::empty_strided         0.14%       1.617ms         0.14%       1.617ms      16.171us          40 B          40 B           100            --
                                            aten::copy_         0.39%       4.451ms         2.34%      26.990ms     103.809us           0 B         -40 B           260            --
                                        cudaMemcpyAsync         1.75%      20.124ms         1.75%      20.124ms      87.495us           0 B           0 B           230            --
                                  cudaStreamSynchronize         3.34%      38.504ms         3.34%      38.504ms     202.653us           0 B           0 B           190            --
                                          model_forward        28.19%     324.594ms        89.43%        1.030s     102.986ms           0 B        -480 B            10            --
                                            aten::empty         1.24%      14.308ms         1.24%      14.308ms       5.864us         480 B         480 B          2440            --
                                            aten::slice         0.15%       1.709ms         0.17%       1.944ms      13.884us           0 B           0 B           140            --
                                        aten::unsqueeze         0.40%       4.608ms         0.46%       5.339ms       6.674us           0 B           0 B           800            --
                                              aten::sub         1.27%      14.614ms         2.29%      26.409ms      35.688us           0 B           0 B           740            --
                                       cudaLaunchKernel        16.94%     195.118ms        16.94%     195.118ms      16.286us           0 B           0 B         11981            --
                                              aten::div         0.18%       2.016ms         0.29%       3.319ms      41.491us           0 B           0 B            80            --
                              aten::upsample_bilinear2d         0.04%     404.400us         0.09%       1.086ms     108.630us           0 B           0 B            10            --
                                           aten::select         0.75%       8.653ms         0.85%       9.782ms      10.632us           0 B           0 B           920            --
                                         aten::new_full         0.01%     141.600us         0.07%     810.900us      81.090us           0 B           0 B            10            --
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 1.152s


  Run         : fcos_r50__baseline__20260613_184128
  Perfetto    : glisser le fichier sur ui.perfetto.dev
  Chrome      : ouvrir chrome://tracing → Load → sélectionner le fichier
  TensorBoard : tensorboard --logdir results\profiler\pytorch\fcos_r50__baseline__20260613_184128\tensorboard
  Résumés     : results\profiler\pytorch\fcos_r50__baseline__20260613_184128/summary*.txt

───────────────────────────────────────────────────────
  efficientdet_d4  [tag=baseline]
───────────────────────────────────────────────────────

==============================================================
  PyTorch Profiler — efficientdet_d4__baseline__20260613_184144
==============================================================
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg       CPU Mem  Self CPU Mem    # of Calls  Total MFLOPs
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                          ProfilerStep*        10.87%     158.583ms       100.00%        1.459s     145.881ms           0 B     -46.88 MB            10            --
                                       aten::lift_fresh         0.00%      48.000us         0.00%      48.000us       4.800us           0 B           0 B            10            --
                                          aten::permute         0.05%     670.500us         0.06%     812.300us       7.385us           0 B           0 B           110            --
                                       aten::as_strided         0.45%       6.557ms         0.45%       6.557ms       1.013us           0 B           0 B          6470            --
                                        aten::unsqueeze         0.37%       5.325ms         0.45%       6.509ms       4.552us           0 B           0 B          1430            --
                                              aten::cat         2.07%      30.188ms         3.87%      56.511ms      92.641us      46.88 MB      46.88 MB           610            --
                                           aten::narrow         0.59%       8.627ms         1.44%      20.991ms      10.044us           0 B           0 B          2090            --
                                            aten::slice         0.72%      10.467ms         0.89%      12.956ms       6.082us           0 B           0 B          2130            --
                                               aten::to         0.06%     806.600us         0.96%      13.941ms      22.485us          40 B           0 B           620            --
                                         aten::_to_copy         0.07%       1.087ms         0.90%      13.134ms     328.355us          40 B           0 B            40            --
                                    aten::empty_strided         0.03%     504.900us         0.03%     504.900us       8.415us          40 B          40 B            60            --
                                            aten::copy_         0.44%       6.473ms         1.59%      23.214ms      42.990us           0 B         -40 B           540            --
                                        cudaMemcpyAsync         0.71%      10.323ms         0.71%      10.323ms     129.036us           0 B           0 B            80            --
                                  cudaStreamSynchronize         0.71%      10.382ms         0.71%      10.382ms     346.063us           0 B           0 B            30            --
                                          model_forward        29.83%     435.226ms        87.95%        1.283s     128.305ms           0 B           0 B            10            --
                                              aten::pad         0.12%       1.819ms         2.46%      35.883ms     102.522us           0 B           0 B           350            --
                                  aten::constant_pad_nd         0.45%       6.550ms         2.34%      34.064ms      97.325us           0 B           0 B           350            --
                                            aten::empty         2.55%      37.204ms         2.55%      37.204ms       3.808us           0 B           0 B          9770            --
                                            aten::fill_         0.22%       3.242ms         0.60%       8.806ms      24.462us           0 B           0 B           360            --
                                       cudaLaunchKernel        12.77%     186.346ms        12.77%     186.346ms      10.463us           0 B           0 B         17810            --
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 1.459s


  Run         : efficientdet_d4__baseline__20260613_184144
  Perfetto    : glisser le fichier sur ui.perfetto.dev
  Chrome      : ouvrir chrome://tracing → Load → sélectionner le fichier
  TensorBoard : tensorboard --logdir results\profiler\pytorch\efficientdet_d4__baseline__20260613_184144\tensorboard
  Résumés     : results\profiler\pytorch\efficientdet_d4__baseline__20260613_184144/summary*.txt

───────────────────────────────────────────────────────
  efficientdet_d5  [tag=baseline]
───────────────────────────────────────────────────────

==============================================================
  PyTorch Profiler — efficientdet_d5__baseline__20260613_184210
==============================================================
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg       CPU Mem  Self CPU Mem    # of Calls  Total MFLOPs
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                          ProfilerStep*        10.30%     167.372ms       100.00%        1.625s     162.518ms           0 B     -46.88 MB            10            --
                                       aten::lift_fresh         0.00%      52.200us         0.00%      52.200us       5.220us           0 B           0 B            10            --
                                          aten::permute         0.04%     672.500us         0.05%     817.800us       7.435us           0 B           0 B           110            --
                                       aten::as_strided         0.41%       6.638ms         0.41%       6.638ms       1.026us           0 B           0 B          6470            --
                                        aten::unsqueeze         0.39%       6.269ms         0.48%       7.752ms       5.421us           0 B           0 B          1430            --
                                              aten::cat         1.92%      31.195ms         3.48%      56.635ms      92.845us      46.88 MB      46.88 MB           610            --
                                           aten::narrow         0.48%       7.799ms         1.16%      18.906ms       9.046us           0 B           0 B          2090            --
                                            aten::slice         0.58%       9.440ms         0.72%      11.749ms       5.516us           0 B           0 B          2130            --
                                               aten::to         0.06%     941.800us         0.96%      15.606ms      25.171us          40 B           0 B           620            --
                                         aten::_to_copy         0.07%       1.136ms         0.90%      14.664ms     366.607us          40 B           0 B            40            --
                                    aten::empty_strided         0.04%     577.000us         0.04%     577.000us       9.617us          40 B          40 B            60            --
                                            aten::copy_         0.44%       7.123ms         1.51%      24.511ms      45.390us           0 B         -40 B           540            --
                                        cudaMemcpyAsync         0.70%      11.457ms         0.70%      11.457ms     143.215us           0 B           0 B            80            --
                                  cudaStreamSynchronize         0.64%      10.468ms         0.64%      10.468ms     348.920us           0 B           0 B            30            --
                                          model_forward        30.39%     493.849ms        88.55%        1.439s     143.908ms           0 B           0 B            10            --
                                              aten::pad         0.10%       1.639ms         2.18%      35.421ms     101.203us           0 B           0 B           350            --
                                  aten::constant_pad_nd         0.39%       6.378ms         2.08%      33.782ms      96.520us           0 B           0 B           350            --
                                            aten::empty         2.50%      40.606ms         2.50%      40.606ms       3.816us           0 B           0 B         10640            --
                                            aten::fill_         0.27%       4.323ms         0.62%      10.076ms      27.989us           0 B           0 B           360            --
                                       cudaLaunchKernel        12.85%     208.834ms        12.85%     208.834ms      10.945us           0 B           0 B         19080            --
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 1.625s



## 12. Benchmark par module — `ModuleBenchmark`

Décomposition du temps GPU **module feuille par module feuille** (Conv2d, BatchNorm2d, ReLU, etc.)
via des CUDA Events attachés en hooks `forward_pre` / `forward`.

**Convention de nommage des sorties :**
```
results/benchmark/modules/<tag>/
    retinanet_r50.csv
    retinanet_r101.csv
    fcos_r50.csv
    ...
```

Changer `BENCH_TAG` pour distinguer les runs (baseline, compiled, tensorrt…).

In [13]:
BENCH_TAG = "baseline"   # changer ici : "compiled", "tensorrt", etc.

# ── Répertoire de sortie ───────────────────────────────────────────────────────
MODULES_OUT = Path("results/benchmark/modules") / BENCH_TAG
MODULES_OUT.mkdir(parents=True, exist_ok=True)

# ── Choix du modèle ───────────────────────────────────────────────────────────
TARGET_MODEL_NAME = "retinanet_r50"
TARGET_MOD        = r50
TARGET_LOAD_FN    = r50.load_model

print(f"Benchmark par module : {TARGET_MODEL_NAME}  [tag={BENCH_TAG}]")
print(f"  warmup={N_WARMUP}, mesure={N_MEASURE}\n")

model_mb = TARGET_LOAD_FN(DEVICE)
mb       = ModuleBenchmark()

result_mb = benchmark_model(model_mb, profile_data, TARGET_MOD.preprocess, TARGET_MOD.collate,
                            n_warmup=N_WARMUP, n_measure=N_MEASURE,
                            device=DEVICE, module_benchmark=mb)
del model_mb; torch.cuda.empty_cache()

# ── Résumé global ─────────────────────────────────────────────────────────────
df_modules  = result_mb["modules"]
sum_modules = df_modules["mean_ms"].sum()
print(f"  Global     : {result_mb['mean_ms']:.2f} ms ± {result_mb['std_ms']:.2f}  ({result_mb['fps']:.1f} FPS)")
print(f"  Σ modules  : {sum_modules:.2f} ms  (parallélisme = {sum_modules/result_mb['mean_ms']:.2f}x)")
print(f"  Nb modules : {len(df_modules)}\n")

# ── Sauvegarde CSV ────────────────────────────────────────────────────────────
csv_path = MODULES_OUT / f"{TARGET_MODEL_NAME}.csv"
df_modules.to_csv(csv_path, index=False)
print(f"  Sauvegardé → {csv_path}\n")

# ── Top 20 modules ────────────────────────────────────────────────────────────
print("Top 20 modules (mean_ms décroissant) :")
display(df_modules.head(20)[["module", "type", "root_component", "mean_ms", "std_ms", "pct_sum", "n_samples"]].round(4))

# ── Agrégation par composant racine ───────────────────────────────────────────
print("\nTemps par composant :")
by_comp = (df_modules.groupby("root_component")["mean_ms"]
           .sum().sort_values(ascending=False).reset_index())
by_comp["pct_total"] = (by_comp["mean_ms"] / sum_modules * 100).round(2)
display(by_comp.round(4))

Benchmark par module : retinanet_r50  [tag=baseline]
  warmup=5, mesure=10

  Global     : 71.44 ms ± 10.29  (14.0 FPS)
  Σ modules  : 26.32 ms  (parallélisme = 0.37x)
  Nb modules : 160

  Sauvegardé → results\benchmark\modules\baseline\retinanet_r50.csv

Top 20 modules (mean_ms décroissant) :

,module,type,root_component,mean_ms,std_ms,pct_sum,n_samples
0,backbone.fpn.layer_blocks.0.0,0,backbone,1.3981,0.0041,5.31,10
1,backbone.body.conv1,conv1,backbone,0.9193,0.1211,3.49,10
2,transform,transform,transform,0.8616,0.4361,3.27,10
3,backbone.body.layer2.0.downsample.0,0,backbone,0.6762,0.0333,2.57,10
4,backbone.body.layer4.0.downsample.0,0,backbone,0.6665,0.0225,2.53,10
5,backbone.body.layer3.0.downsample.0,0,backbone,0.6422,0.0448,2.44,10
6,backbone.body.layer4.0.conv2,conv2,backbone,0.6272,0.0476,2.38,10
7,backbone.body.layer4.2.conv2,conv2,backbone,0.5690,0.0434,2.16,10
8,backbone.body.layer4.1.conv2,conv2,backbone,0.5471,0.0028,2.08,10
9,anchor_generator,anchor_generator,anchor_generator,0.4838,0.1550,1.84,10
10,backbone.body.layer1.1.conv2,conv2,backbone,0.4469,0.1387,1.70,10
11,backbone.fpn.extra_blocks.p6,p6,backbone,0.4383,0.0023,1.67,10
12,backbone.body.layer1.0.conv2,conv2,backbone,0.4340,0.1145,1.65,10
13,backbone.body.layer1.2.conv2,conv2,backbone,0.4188,0.0843,1.59,10
14,backbone.body.layer2.0.conv2,conv2,backbone,0.3890,0.0436,1.48,10
15,backbone.fpn.layer_blocks.1.0,0,backbone,0.3753,0.0524,1.43,10
16,backbone.body.layer3.4.conv2,conv2,backbone,0.3745,0.0613,1.42,10
17,backbone.body.layer3.3.conv2,conv2,backbone,0.3699,0.0558,1.41,10
18,backbone.body.layer3.0.conv2,conv2,backbone,0.3680,0.0403,1.40,10
19,backbone.body.layer3.2.conv2,conv2,backbone,0.3602,0.0472,1.37,10

Temps par composant :

     root_component  mean_ms  pct_total
0          backbone  22.8399      86.79
1              head   2.1312       8.10
2         transform   0.8616       3.27
3  anchor_generator   0.4838       1.84

In [14]:
# ── Benchmark par module sur tous les modèles ─────────────────────────────────
# BENCH_TAG défini dans la cellule précédente — changer là-bas pour un nouveau run
MODELS_TO_BENCH = {
    "retinanet_r50":   (r50,  r50.load_model),
    "retinanet_r101":  (r101, r101.load_model),
    "fcos_r50":        (fcos, fcos.load_model),
    "efficientdet_d4": (ed4,  ed4.load_model),
    "efficientdet_d5": (ed5,  ed5.load_model),
    "efficientdet_d6": (ed6,  ed6.load_model),
}

all_modules = {}
all_globals = {}

for mname, (mod, load_fn) in MODELS_TO_BENCH.items():
    print(f"  {mname}…", end=" ", flush=True)
    m  = load_fn(DEVICE)
    mb = ModuleBenchmark()
    res = benchmark_model(m, profile_data, mod.preprocess, mod.collate,
                          n_warmup=N_WARMUP, n_measure=N_MEASURE,
                          device=DEVICE, module_benchmark=mb)
    all_modules[mname] = res["modules"]
    all_globals[mname] = {k: v for k, v in res.items() if k != "modules"}
    del m; torch.cuda.empty_cache()

    csv_path = MODULES_OUT / f"{mname}.csv"
    res["modules"].to_csv(csv_path, index=False)
    print(f"{res['mean_ms']:.1f} ms  ({res['fps']:.1f} FPS)  — {len(res['modules'])} modules  → {csv_path}")

print(f"\nCSV sauvegardés dans : {MODULES_OUT.resolve()}")

print("\n=== Top 5 modules les plus lents par modèle ===")
for mname, df in all_modules.items():
    print(f"\n{mname} (global={all_globals[mname]['mean_ms']:.1f} ms):")
    display(df.head(5)[["module", "mean_ms", "pct_sum"]].round(4))

  retinanet_r50… 96.0 ms  (10.4 FPS)  — 160 modules  → results\benchmark\modules\baseline\retinanet_r50.csv
  retinanet_r101…

WARNING:fvcore.common.config:Loading config d:\school\ProjectDSAI2026_2\detectron2\model_zoo\configs\COCO-Detection\../Base-RetinaNet.yaml with yaml.unsafe_load. Your machine may be at risk if the file contains malicious content.
WARNING:fvcore.common.checkpoint:The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std

82.6 ms  (12.1 FPS)  — 130 modules  → results\benchmark\modules\baseline\retinanet_r101.csv
  fcos_r50… 62.7 ms  (15.9 FPS)  — 161 modules  → results\benchmark\modules\baseline\fcos_r50.csv
  efficientdet_d4… 123.1 ms  (8.1 FPS)  — 898 modules  → results\benchmark\modules\baseline\efficientdet_d4.csv
  efficientdet_d5… 148.7 ms  (6.7 FPS)  — 1000 modules  → results\benchmark\modules\baseline\efficientdet_d5.csv
  efficientdet_d6… 156.0 ms  (6.4 FPS)  — 1155 modules  → results\benchmark\modules\baseline\efficientdet_d6.csv

CSV sauvegardés dans : D:\school\ProjectDSAI2026_2\results\benchmark\modules\baseline

=== Top 5 modules les plus lents par modèle ===

retinanet_r50 (global=96.0 ms):

                                module  mean_ms  pct_sum
0        backbone.fpn.layer_blocks.0.0   1.3593     4.00
1                     anchor_generator   1.2605     3.71
2                            transform   1.0764     3.17
3                  backbone.body.conv1   0.9714     2.86
4  backbone.body.layer4.0.downsample.0   0.7338     2.16

retinanet_r101 (global=82.6 ms):

                                    module  mean_ms  pct_sum
0                     backbone.fpn_output3   1.3973    15.63
1                    backbone.top_block.p6   0.4378     4.90
2                     backbone.fpn_output4   0.3516     3.93
3                    backbone.fpn_lateral3   0.2860     3.20
4  backbone.bottom_up.res2.0.shortcut.norm   0.2118     2.37

fcos_r50 (global=62.7 ms):

                                module  mean_ms  pct_sum
0        backbone.fpn.layer_blocks.0.0   1.3950     4.77
1                  backbone.body.conv1   0.8811     3.01
2  backbone.body.layer4.0.downsample.0   0.6830     2.33
3  backbone.body.layer2.0.downsample.0   0.6699     2.29
4  backbone.body.layer3.0.downsample.0   0.6551     2.24

efficientdet_d4 (global=123.1 ms):

                              module  mean_ms  pct_sum
0  model.backbone.blocks.1.0.conv_dw   1.1077     1.83
1  model.backbone.blocks.0.0.conv_dw   0.5230     0.87
2  model.backbone.blocks.1.2.conv_dw   0.4996     0.83
3  model.backbone.blocks.1.3.conv_dw   0.4991     0.83
4  model.backbone.blocks.1.1.conv_dw   0.4988     0.83

efficientdet_d5 (global=148.7 ms):

                              module  mean_ms  pct_sum
0  model.backbone.blocks.1.0.conv_dw   1.1193     1.48
1  model.backbone.blocks.1.4.conv_dw   0.6422     0.85
2  model.backbone.blocks.1.3.conv_dw   0.6393     0.85
3  model.backbone.blocks.1.2.conv_dw   0.6382     0.85
4  model.backbone.blocks.1.1.conv_dw   0.6371     0.84

efficientdet_d6 (global=156.0 ms):

                              module  mean_ms  pct_sum
0  model.backbone.blocks.1.0.conv_dw   1.4200     1.62
1  model.backbone.blocks.1.5.conv_dw   0.6603     0.75
2  model.backbone.blocks.1.1.conv_dw   0.6363     0.72
3  model.backbone.blocks.1.3.conv_dw   0.6349     0.72
4  model.backbone.blocks.1.4.conv_dw   0.6348     0.72