# Test Benchmark — Mini protocole

Protocole réduit pour valider le pipeline avant le benchmark complet.

| Paramètre | Valeur |
|---|---|
| Images profiling | 30 (640×640) |
| Images MAP | 10 (résolution originale) |
| Warmup | 5 itérations |
| Mesure | 10 itérations |
| Seed | 42 |

**Deux modes distincts :**
- **Profiling** → `load_model()` + `preprocess()` : images 640×640, comparaison de vitesse standardisée
- **MAP eval** → `load_model_eval()` + `evaluate_map()` : résolution native du modèle, conforme COCO

## 1. Configuration

In [1]:
import sys, os
sys.path.insert(0, os.path.abspath("."))

import torch
import numpy as np
import pandas as pd
from pathlib import Path

IMG_DIR     = "datasets/coco/val2017"
ANN_FILE    = "datasets/coco/annotations/instances_val2017.json"
RESULTS_DIR = Path("results")
RESULTS_DIR.mkdir(exist_ok=True)

N_PROFILE_IMAGES = 300
N_EVAL_IMAGES    = 10
N_WARMUP         = 5
N_MEASURE        = 10
SEED             = 42
DEVICE           = "cuda" if torch.cuda.is_available() else "cpu"

print(f"Device : {DEVICE}")
if DEVICE == "cuda":
    print(f"GPU    : {torch.cuda.get_device_name(0)}")
    print(f"VRAM   : {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

Device : cuda
GPU    : NVIDIA GeForce RTX 5060 Laptop GPU
VRAM   : 8.5 GB

## 2. Chargement des données

- `load_profiling_data` → images redimensionnées à 640×640
- `load_eval_data` → images à résolution originale COCO (variable)

In [2]:
from utils.data_loader import load_profiling_data, load_eval_data

profile_data        = load_profiling_data(IMG_DIR, ANN_FILE, n=N_PROFILE_IMAGES, seed=SEED)
eval_data, coco_gt  = load_eval_data(IMG_DIR, ANN_FILE, n=N_EVAL_IMAGES, seed=SEED)

print(profile_data)           # LazySampleList(n=30, ...)
print(f"Premier sample profiling : {profile_data[0]}")
print(f"Premier sample eval      : {eval_data[0]}")

loading annotations into memory...
Done (t=0.49s)
creating index...
index created!
loading annotations into memory...
Done (t=0.42s)
creating index...
index created!
LazySampleList(n=300, img_dir='datasets/coco/val2017')
Premier sample profiling : {'image_id': 107554, 'path': 'datasets\\coco\\val2017\\000000107554.jpg', 'orig_size': (480, 640)}
Premier sample eval      : {'image_id': 107554, 'path': 'datasets\\coco\\val2017\\000000107554.jpg', 'orig_size': (480, 640)}

## 3. Fonctions utilitaires

In [3]:
from utils.profiler import profile_model

# Accumulateurs pour les CSV finaux
profiling_rows, map_rows = [], []

def record(name, prof, maps):
    profiling_rows.append({"model": name, **prof})
    map_rows.append({"model": name, **maps})
    print(f"  Profiling (640×640) : {prof['mean_ms']:.1f} ms ± {prof['std_ms']:.1f}  ({prof['fps']:.1f} FPS)")
    print(f"  MAP (native res)    : AP={maps.get('AP', -1):.3f}  AP50={maps.get('AP50', -1):.3f}")

print("OK — profile_model importé depuis utils/profiler.py")

OK — profile_model importé depuis utils/profiler.py

## 4. RetinaNet R50

In [4]:
import models.retinanet_r50 as r50

print("Chargement profiling model...")
model_r50 = r50.load_model(DEVICE)
prof_r50  = profile_model(model_r50, profile_data, r50.preprocess, r50.collate,
                          n_warmup=N_WARMUP, n_measure=N_MEASURE, device=DEVICE)
del model_r50; torch.cuda.empty_cache()

print("Chargement eval model + MAP...")
model_r50_eval = r50.load_model_eval(DEVICE)
map_r50        = r50.evaluate_map(model_r50_eval, eval_data, coco_gt, DEVICE)
del model_r50_eval; torch.cuda.empty_cache()

record("retinanet_r50", prof_r50, map_r50)

Chargement profiling model...
Chargement eval model + MAP...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.12s).
Accumulating evaluation results...
DONE (t=0.08s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.525
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.820
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.535
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.305
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.546
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.728
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.428
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.537
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.573
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.307
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.622
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.768
  Profiling (640×640) : 63.2 ms ± 1.8  (15.8 FPS)
  MAP (native res)    : AP=0.525  AP50=0.820

## 5. RetinaNet R101

In [5]:
import models.retinanet_r101 as r101

print("Chargement profiling model...")
model_r101 = r101.load_model(DEVICE)
prof_r101  = profile_model(model_r101, profile_data, r101.preprocess, r101.collate,
                           n_warmup=N_WARMUP, n_measure=N_MEASURE, device=DEVICE)
del model_r101; torch.cuda.empty_cache()

print("Chargement eval model + MAP...")
model_r101_eval = r101.load_model_eval(DEVICE)
map_r101        = r101.evaluate_map(model_r101_eval, eval_data, coco_gt, DEVICE)
del model_r101_eval; torch.cuda.empty_cache()

record("retinanet_r101", prof_r101, map_r101)

Loading config d:\school\ProjectDSAI2026_2\detectron2\model_zoo\configs\COCO-Detection\../Base-RetinaNet.yaml with yaml.unsafe_load. Your machine may be at risk if the file contains malicious content.

Chargement profiling model...

The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std
c:\ProgramData\anaconda3\Lib\site-packages\torch\functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:4324.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Loading config d:\school\ProjectDSAI2026_2\detectron2\model_zoo\configs\COCO-Detection\../Base-RetinaNet.yaml with yaml.unsafe_load. Your machine may be at risk if the file contains malicious content.

Chargement eval model + MAP...

The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std

Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.06s).
Accumulating evaluation results...
DONE (t=0.06s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.474
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.708
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.494
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.203
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.520
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.708
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.371
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.519
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.573
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.265
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.623
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.736
  Profiling (640×640) : 75.7 ms ± 7.1  (13.2 FPS)
  MAP (native res)    : AP=0.474  AP50=0.708

## 6. FCOS R50

In [6]:
import models.fcos_r50 as fcos

print("Chargement profiling model...")
model_fcos = fcos.load_model(DEVICE)
prof_fcos  = profile_model(model_fcos, profile_data, fcos.preprocess, fcos.collate,
                           n_warmup=N_WARMUP, n_measure=N_MEASURE, device=DEVICE)
del model_fcos; torch.cuda.empty_cache()

print("Chargement eval model + MAP...")
model_fcos_eval = fcos.load_model_eval(DEVICE)
map_fcos        = fcos.evaluate_map(model_fcos_eval, eval_data, coco_gt, DEVICE)
del model_fcos_eval; torch.cuda.empty_cache()

record("fcos_r50", prof_fcos, map_fcos)

Chargement profiling model...
Chargement eval model + MAP...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.43s).
Accumulating evaluation results...
DONE (t=0.30s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.514
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.764
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.580
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.366
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.533
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.674
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.389
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.541
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.569
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.379
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.601
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.761
  Profiling (640×640) : 60.7 ms ± 6.2  (16.5 FPS)
  MAP (native res)    : AP=0.514  AP50=0.764

## 7. EfficientDet — test pipeline (PIL + F.normalize, sans +1)

In [7]:
# ── Test rapide D4 avec le pipeline PIL copié de l'ancien code ──────────────────
import importlib
import models.efficientdet_d4 as ed4
importlib.reload(ed4)

print("Chargement D4 eval model...")
model_ed4_test = ed4.load_model_eval(DEVICE)

print(f"Évaluation MAP sur {N_EVAL_IMAGES} images...")
map_ed4_test = ed4.evaluate_map(model_ed4_test, eval_data, coco_gt, DEVICE)
del model_ed4_test; torch.cuda.empty_cache()

print(f"\n>>> D4 AP  = {map_ed4_test['AP']:.4f}  (attendu ~0.43)")
print(f">>> D4 AP50= {map_ed4_test['AP50']:.4f}  (attendu ~0.62)")
print(f"\nRésultat complet : {map_ed4_test}")

Chargement D4 eval model...
Évaluation MAP sur 10 images...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.05s).
Accumulating evaluation results...
DONE (t=0.06s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.582
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.738
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.633
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.362
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.593
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.879
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.459
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.618
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.648
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.421
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.608
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.896

>>> D4 AP  = 0.5817  (attendu ~0.43)
>>> D4 AP50= 0.7383  (attendu ~0.62)

Résultat complet : {'AP': 0.5817148031511211, 'AP50': 0.7383492874174296, 'AP75': 0.6334692292758687, 'APs': 0.3616336633663366, 'APm': 0.5927392739273927, 'APl': 0.8789250353606789}

In [8]:
import models.efficientdet_d4 as ed4

print("Chargement profiling model...")
model_ed4 = ed4.load_model(DEVICE)
prof_ed4  = profile_model(model_ed4, profile_data, ed4.preprocess, ed4.collate,
                          n_warmup=N_WARMUP, n_measure=N_MEASURE, device=DEVICE)
del model_ed4; torch.cuda.empty_cache()

print("Chargement eval model + MAP...")
model_ed4_eval = ed4.load_model_eval(DEVICE)
map_ed4        = ed4.evaluate_map(model_ed4_eval, eval_data, coco_gt, DEVICE)
del model_ed4_eval; torch.cuda.empty_cache()

record("efficientdet_d4", prof_ed4, map_ed4)

Chargement profiling model...
Chargement eval model + MAP...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.18s).
Accumulating evaluation results...
DONE (t=0.23s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.582
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.738
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.633
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.362
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.593
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.879
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.459
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.618
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.648
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.421
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.608
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.896
  Profiling (640×640) : 67.1 ms ± 7.8  (14.9 FPS)
  MAP (native res)    : AP=0.582  AP50=0.738

## 8. EfficientDet D5

In [9]:
import models.efficientdet_d5 as ed5

print("Chargement profiling model...")
model_ed5 = ed5.load_model(DEVICE)
prof_ed5  = profile_model(model_ed5, profile_data, ed5.preprocess, ed5.collate,
                          n_warmup=N_WARMUP, n_measure=N_MEASURE, device=DEVICE)
del model_ed5; torch.cuda.empty_cache()

print("Chargement eval model + MAP...")
model_ed5_eval = ed5.load_model_eval(DEVICE)
map_ed5        = ed5.evaluate_map(model_ed5_eval, eval_data, coco_gt, DEVICE)
del model_ed5_eval; torch.cuda.empty_cache()

record("efficientdet_d5", prof_ed5, map_ed5)

Chargement profiling model...
Chargement eval model + MAP...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.06s).
Accumulating evaluation results...
DONE (t=0.06s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.524
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.728
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.605
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.417
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.573
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.764
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.415
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.555
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.587
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.428
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.583
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.829
  Profiling (640×640) : 65.0 ms ± 3.4  (15.4 FPS)
  MAP (native res)    : AP=0.524  AP50=0.728

## 9. EfficientDet D6

In [10]:
import models.efficientdet_d6 as ed6

print("Chargement profiling model...")
model_ed6 = ed6.load_model(DEVICE)
prof_ed6  = profile_model(model_ed6, profile_data, ed6.preprocess, ed6.collate,
                          n_warmup=N_WARMUP, n_measure=N_MEASURE, device=DEVICE)
del model_ed6; torch.cuda.empty_cache()

print("Chargement eval model + MAP...")
model_ed6_eval = ed6.load_model_eval(DEVICE)
map_ed6        = ed6.evaluate_map(model_ed6_eval, eval_data, coco_gt, DEVICE)
del model_ed6_eval; torch.cuda.empty_cache()

record("efficientdet_d6", prof_ed6, map_ed6)

Chargement profiling model...
Chargement eval model + MAP...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.09s).
Accumulating evaluation results...
DONE (t=0.10s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.507
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.692
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.532
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.295
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.561
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.760
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.374
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.584
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.620
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.356
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.589
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.893
  Profiling (640×640) : 82.4 ms ± 13.1  (12.1 FPS)
  MAP (native res)    : AP=0.507  AP50=0.692

## 10. Résultats

In [11]:
df_prof = pd.DataFrame(profiling_rows).set_index("model")
df_map  = pd.DataFrame(map_rows).set_index("model")

df_prof.to_csv(RESULTS_DIR / "profiling_test.csv")
df_map.to_csv(RESULTS_DIR  / "map_test.csv")

print("=== Profiling — 640×640 (ms) ===")
display(df_prof.round(2))

print("\n=== MAP — résolution native COCO ===")
display(df_map.round(3))

print(f"\nCSV sauvegardés dans {RESULTS_DIR.resolve()}")

=== Profiling — 640×640 (ms) ===

                 mean_ms  std_ms  min_ms  max_ms    fps
model
retinanet_r50      63.21    1.82   59.81   66.36  15.82
retinanet_r101     75.66    7.09   69.53   94.95  13.22
fcos_r50           60.71    6.20   55.04   77.93  16.47
efficientdet_d4    67.10    7.83   57.07   85.81  14.90
efficientdet_d5    65.00    3.42   60.61   71.66  15.39
efficientdet_d6    82.40   13.07   76.21  121.49  12.14

=== MAP — résolution native COCO ===

                    AP   AP50   AP75    APs    APm    APl
model
retinanet_r50    0.525  0.820  0.535  0.305  0.546  0.728
retinanet_r101   0.474  0.708  0.494  0.203  0.520  0.708
fcos_r50         0.514  0.764  0.580  0.366  0.533  0.674
efficientdet_d4  0.582  0.738  0.633  0.362  0.593  0.879
efficientdet_d5  0.524  0.728  0.605  0.417  0.573  0.764
efficientdet_d6  0.507  0.692  0.532  0.295  0.561  0.760

CSV sauvegardés dans D:\school\ProjectDSAI2026_2\results

## 11. Profilage méso-scopique — PyTorch Profiler

Décomposition du forward pass par opération PyTorch (couche par couche).

Le profiler utilise son propre `schedule(wait=0, warmup=N_WARMUP, active=N_MEASURE)` :
- phase warmup : GPU chauffe, trace collectée mais non commitée
- phase active : trace exportée vers TensorBoard + Chrome JSON

**Sorties :**
```
results/profiler/pytorch/<model>/
  tensorboard/        ← tensorboard --logdir results/profiler/pytorch/<model>/tensorboard
  chrome_trace.json   ← chrome://tracing  ou  ui.perfetto.dev
  summary*.txt        ← tableaux triés par cuda_time_total
```

In [12]:
from profiler.pytorch_profiler import profile_with_pytorch

PROF_OUTPUT  = "results/profiler/pytorch"
PROFILER_TAG = "baseline"   # modifier ici pour les runs suivants : "tensorRt", "compiled", etc.

MODELS_TO_PROFILE = {
    "retinanet_r50":   (r50,  r50.load_model),
    "retinanet_r101":  (r101, r101.load_model),
    "fcos_r50":        (fcos, fcos.load_model),
    "efficientdet_d4": (ed4,  ed4.load_model),
    "efficientdet_d5": (ed5,  ed5.load_model),
    "efficientdet_d6": (ed6,  ed6.load_model),
}

pytorch_prof_results = {}

for model_name, (mod, load_fn) in MODELS_TO_PROFILE.items():
    print(f"\n{'─'*55}")
    print(f"  Profiling : {model_name}  [tag={PROFILER_TAG}]")
    print(f"{'─'*55}")

    model = load_fn(DEVICE)

    result = profile_with_pytorch(
        model         = model,
        data          = profile_data,
        preprocess_fn = mod.preprocess,
        collate_fn    = mod.collate,
        n_warmup      = N_WARMUP,
        n_active      = N_MEASURE,
        output_dir    = PROF_OUTPUT,
        model_name    = model_name,
        tag           = PROFILER_TAG,
        device        = DEVICE,
    )

    pytorch_prof_results[model_name] = result
    del model
    torch.cuda.empty_cache()

print(f"\n✓ Profiling terminé.")
print(f"  TensorBoard : tensorboard --logdir {PROF_OUTPUT}")

───────────────────────────────────────────────────────
  Profiling : retinanet_r50  [tag=baseline]
───────────────────────────────────────────────────────

==============================================================
  PyTorch Profiler — retinanet_r50—baseline—20260610_002234
==============================================================
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg       CPU Mem  Self CPU Mem      CUDA Mem  Self CUDA Mem    # of Calls  Total KFLOPs
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                          model_forward         0.00%       0.000us         0.00%       0.000us       0.000us     735.657ms       151.68%     735.657ms      73.566ms           0 B           0 B           0 B           0 B            10            --
                                          ProfilerStep*        11.59%      98.561ms       100.00%     850.379ms      85.038ms       0.000us         0.00%     485.061ms      48.506ms           0 B           0 B           0 B     -46.88 MB            10            --
                                          model_forward        21.48%     182.638ms        87.12%     740.847ms      74.085ms       0.000us         0.00%     480.702ms      48.070ms           0 B        -880 B           0 B     -10.11 GB            10            --
                                           aten::conv2d         0.71%       6.035ms        12.32%     104.727ms      94.348us       0.000us         0.00%     397.323ms     357.948us           0 B           0 B       4.61 GB           0 B          1110  1945861504.000
                                      aten::convolution         0.90%       7.677ms        11.61%      98.692ms      88.912us       0.000us         0.00%     397.323ms     357.948us           0 B           0 B       4.61 GB           0 B          1110            --
                                     aten::_convolution         1.42%      12.040ms        10.70%      91.015ms      81.995us       0.000us         0.00%     397.323ms     357.948us           0 B           0 B       4.61 GB           0 B          1110            --
                                aten::cudnn_convolution         5.01%      42.609ms         8.73%      74.253ms      66.894us     394.405ms        81.32%     394.405ms     355.320us           0 B           0 B       4.61 GB       4.61 GB          1110            --
_ZN17cutlass__5x_cudnn6KernelI66cutlass_tensorop_s16...         0.00%       0.000us         0.00%       0.000us       0.000us     227.355ms        46.88%     227.355ms     421.028us           0 B           0 B           0 B           0 B           540            --
_ZN5cudnn19engines_precompiled16nchwToNhwcKernelIfff...         0.00%       0.000us         0.00%       0.000us       0.000us      28.385ms         5.85%      28.385ms      23.654us           0 B           0 B           0 B           0 B          1200            --
                                       aten::batch_norm         0.32%       2.732ms         4.84%      41.174ms      77.687us       0.000us         0.00%      20.044ms      37.819us           0 B           0 B       3.52 GB           0 B           530            --
                           aten::_batch_norm_impl_index         0.47%       4.011ms         4.52%      38.442ms      72.533us       0.000us         0.00%      20.044ms      37.819us           0 B           0 B       3.52 GB           0 B           530            --
                                 aten::cudnn_batch_norm         2.00%      17.016ms         4.05%      34.431ms      64.964us      20.044ms         4.13%      20.044ms      37.819us           0 B           0 B       3.52 GB           0 B           530            --
_ZN5cudnn26bn_fw_inf_1C11_kernel_NCHWIffLb1ELi1EEEvT...         0.00%       0.000us         0.00%       0.000us       0.000us      20.044ms         4.13%      20.044ms      37.819us           0 B           0 B           0 B           0 B           530            --
_Z22tensorTransformGenericIfffLb1ELb0ELb0EL21cudnnKe...         0.00%       0.000us         0.00%       0.000us       0.000us      16.527ms         3.41%      16.527ms     826.364us           0 B           0 B           0 B           0 B            20            --
sm80_xmma_fprop_implicit_gemm_tf32f32_tf32f32_f32_nh...         0.00%       0.000us         0.00%       0.000us       0.000us      14.903ms         3.07%      14.903ms     372.574us           0 B           0 B           0 B           0 B            40            --
_ZN7cutlass7Kernel2I52cutlass_80_tensorop_s1688gemm_...         0.00%       0.000us         0.00%       0.000us       0.000us      14.426ms         2.97%      14.426ms     144.256us           0 B           0 B           0 B           0 B           100            --
                                             aten::add_         0.50%       4.293ms         0.88%       7.488ms      22.022us      14.375ms         2.96%      14.375ms      42.280us           0 B           0 B           0 B           0 B           340            --
_Z23implicit_convolve_sgemmIffLi1024ELi5ELi5ELi3ELi3...         0.00%       0.000us         0.00%       0.000us       0.000us      14.294ms         2.95%      14.294ms     714.680us           0 B           0 B           0 B           0 B            20            --
_ZN2at6native29vectorized_elementwise_kernelILi4EZZZ...         0.00%       0.000us         0.00%       0.000us       0.000us      12.679ms         2.61%      12.679ms      12.807us           0 B           0 B           0 B           0 B           990            --
_Z26precomputed_convolve_sgemmIfLi1024ELi5ELi5ELi4EL...         0.00%       0.000us         0.00%       0.000us       0.000us      12.573ms         2.59%      12.573ms     628.639us           0 B           0 B           0 B           0 B            20            --
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 850.389ms
Self CUDA time total: 484.999ms


  Run         : retinanet_r50—baseline—20260610_002234
  TensorBoard : tensorboard --logdir results\profiler\pytorch\retinanet_r50—baseline—20260610_002234
  Perfetto    : ouvrir le .pt.trace.json de results\profiler\pytorch\retinanet_r50—baseline—20260610_002234\tensorboard
  Résumés     : results\profiler\pytorch\retinanet_r50—baseline—20260610_002234/summary*.txt

WARNING:fvcore.common.config:Loading config d:\school\ProjectDSAI2026_2\detectron2\model_zoo\configs\COCO-Detection\../Base-RetinaNet.yaml with yaml.unsafe_load. Your machine may be at risk if the file contains malicious content.

───────────────────────────────────────────────────────
  Profiling : retinanet_r101  [tag=baseline]
───────────────────────────────────────────────────────

WARNING:fvcore.common.checkpoint:The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std

==============================================================
  PyTorch Profiler — retinanet_r101—baseline—20260610_002305
==============================================================
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg       CPU Mem  Self CPU Mem      CUDA Mem  Self CUDA Mem    # of Calls  Total KFLOPs
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                          model_forward         0.00%       0.000us         0.00%       0.000us       0.000us     861.782ms       151.37%     861.782ms      86.178ms           0 B           0 B           0 B           0 B            10            --
                                          ProfilerStep*         8.81%      84.753ms       100.00%     961.488ms      96.149ms       0.000us         0.00%     569.538ms      56.954ms           0 B           0 B           0 B     -46.88 MB            10            --
                                          model_forward        23.31%     224.162ms        90.04%     865.750ms      86.575ms       0.000us         0.00%     563.648ms      56.365ms           0 B     -13.44 KB           0 B     -12.71 GB            10            --
                                           aten::conv2d         1.01%       9.666ms        17.15%     164.862ms     101.767us       0.000us         0.00%     477.666ms     294.856us           0 B           0 B       6.14 GB           0 B          1620  2475299328.000
                                      aten::convolution         1.20%      11.566ms        16.14%     155.197ms      95.800us       0.000us         0.00%     477.666ms     294.856us           0 B           0 B       6.14 GB           0 B          1620            --
                                     aten::_convolution         1.86%      17.867ms        14.94%     143.631ms      88.661us       0.000us         0.00%     477.666ms     294.856us           0 B           0 B       6.14 GB           0 B          1620            --
                                aten::cudnn_convolution         6.55%      62.987ms        11.57%     111.280ms      68.691us     470.110ms        82.57%     470.216ms     290.257us           0 B           0 B       6.14 GB       6.14 GB          1620            --
_ZN17cutlass__5x_cudnn6KernelI66cutlass_tensorop_s16...         0.00%       0.000us         0.00%       0.000us       0.000us     271.148ms        47.63%     271.148ms     381.898us           0 B           0 B           0 B           0 B           710            --
_ZN7cutlass7Kernel2I52cutlass_80_tensorop_s1688gemm_...         0.00%       0.000us         0.00%       0.000us       0.000us      37.479ms         6.58%      37.479ms     138.813us           0 B           0 B           0 B           0 B           270            --
_ZN5cudnn19engines_precompiled16nchwToNhwcKernelIfff...         0.00%       0.000us         0.00%       0.000us       0.000us      36.436ms         6.40%      36.436ms      23.357us           0 B           0 B           0 B           0 B          1560            --
                                       aten::batch_norm         0.55%       5.332ms         8.97%      86.248ms      82.931us       0.000us         0.00%      30.447ms      29.276us           0 B           0 B       5.14 GB           0 B          1040            --
                           aten::_batch_norm_impl_index         0.76%       7.287ms         8.42%      80.916ms      77.804us       0.000us         0.00%      30.447ms      29.276us           0 B           0 B       5.14 GB           0 B          1040            --
                                 aten::cudnn_batch_norm         3.81%      36.680ms         7.66%      73.630ms      70.798us      30.447ms         5.35%      30.447ms      29.276us           0 B           0 B       5.14 GB           0 B          1040            --
_ZN5cudnn26bn_fw_inf_1C11_kernel_NCHWIffLb1ELi1EEEvT...         0.00%       0.000us         0.00%       0.000us       0.000us      30.447ms         5.35%      30.447ms      29.276us           0 B           0 B           0 B           0 B          1040            --
_ZN7cutlass7Kernel2I52cutlass_80_tensorop_s1688gemm_...         0.00%       0.000us         0.00%       0.000us       0.000us      27.146ms         4.77%      27.146ms     118.024us           0 B           0 B           0 B           0 B           230            --
                                             aten::add_         1.08%      10.375ms         2.03%      19.539ms      21.472us      22.361ms         3.93%      22.361ms      24.573us           0 B           0 B           0 B           0 B           910            --
_ZN2at6native29vectorized_elementwise_kernelILi4EZZZ...         0.00%       0.000us         0.00%       0.000us       0.000us      17.159ms         3.01%      17.159ms      11.393us           0 B           0 B           0 B           0 B          1506            --
_Z23implicit_convolve_sgemmIffLi1024ELi5ELi5ELi3ELi3...         0.00%       0.000us         0.00%       0.000us       0.000us      16.055ms         2.82%      16.055ms     535.159us           0 B           0 B           0 B           0 B            30            --
_Z26precomputed_convolve_sgemmIfLi1024ELi5ELi5ELi4EL...         0.00%       0.000us         0.00%       0.000us       0.000us      16.009ms         2.81%      16.009ms     400.220us           0 B           0 B           0 B           0 B            40            --
_ZN2at6native29vectorized_elementwise_kernelILi4ENS0...         0.00%       0.000us         0.00%       0.000us       0.000us      15.901ms         2.79%      15.901ms      24.539us           0 B           0 B           0 B           0 B           648            --
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 961.496ms
Self CUDA time total: 569.325ms


  Run         : retinanet_r101—baseline—20260610_002305
  TensorBoard : tensorboard --logdir results\profiler\pytorch\retinanet_r101—baseline—20260610_002305
  Perfetto    : ouvrir le .pt.trace.json de results\profiler\pytorch\retinanet_r101—baseline—20260610_002305\tensorboard
  Résumés     : results\profiler\pytorch\retinanet_r101—baseline—20260610_002305/summary*.txt

───────────────────────────────────────────────────────
  Profiling : fcos_r50  [tag=baseline]
───────────────────────────────────────────────────────

==============================================================
  PyTorch Profiler — fcos_r50—baseline—20260610_002332
==============================================================
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg       CPU Mem  Self CPU Mem      CUDA Mem  Self CUDA Mem    # of Calls  Total MFLOPs
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                          model_forward         0.00%       0.000us         0.00%       0.000us       0.000us     736.477ms       163.28%     736.477ms      73.648ms           0 B           0 B           0 B           0 B            10            --
                                          ProfilerStep*         9.89%      82.359ms       100.00%     833.013ms      83.301ms       0.000us         0.00%     451.234ms      45.123ms           0 B           0 B           0 B     -46.88 MB            10            --
                                          model_forward        26.73%     222.698ms        89.11%     742.326ms      74.233ms       0.000us         0.00%     447.594ms      44.759ms           0 B        -480 B           0 B     -13.15 GB            10            --
                                           aten::conv2d         0.96%       7.971ms        18.55%     154.565ms     133.246us       0.000us         0.00%     347.283ms     299.382us           0 B           0 B       4.32 GB           0 B          1160   1639444.480
                                      aten::convolution         1.16%       9.668ms        17.60%     146.594ms     126.374us       0.000us         0.00%     347.283ms     299.382us           0 B           0 B       4.32 GB           0 B          1160            --
                                     aten::_convolution         2.24%      18.700ms        16.44%     136.926ms     118.040us       0.000us         0.00%     347.283ms     299.382us           0 B           0 B       4.32 GB           0 B          1160            --
                                aten::cudnn_convolution         6.57%      54.728ms        11.99%      99.917ms      86.135us     340.890ms        75.58%     341.071ms     294.027us           0 B           0 B       4.32 GB       4.32 GB          1160            --
_ZN17cutlass__5x_cudnn6KernelI66cutlass_tensorop_s16...         0.00%       0.000us         0.00%       0.000us       0.000us     191.258ms        42.40%     191.258ms     347.742us           0 B           0 B           0 B           0 B           550            --
_ZN2at6native18elementwise_kernelILi128ELi2EZNS0_22g...         0.00%       0.000us         0.00%       0.000us       0.000us      30.463ms         6.75%      30.463ms      20.639us           0 B           0 B           0 B           0 B          1476            --
                                              aten::add         2.68%      22.349ms         4.88%      40.646ms      30.108us      25.319ms         5.61%      25.319ms      18.755us           0 B           0 B       3.56 GB       3.56 GB          1350       928.393
                                              aten::mul         2.95%      24.575ms         5.50%      45.782ms      23.599us      24.659ms         5.47%      24.659ms      12.711us           0 B           0 B       3.51 GB       3.51 GB          1940       915.596
_ZN5cudnn19engines_precompiled16nchwToNhwcKernelIfff...         0.00%       0.000us         0.00%       0.000us       0.000us      23.827ms         5.28%      23.827ms      19.062us           0 B           0 B           0 B           0 B          1250            --
_ZN2at6native18elementwise_kernelILi128ELi2EZNS0_22g...         0.00%       0.000us         0.00%       0.000us       0.000us      21.733ms         4.82%      21.733ms      34.497us           0 B           0 B           0 B           0 B           630            --
sm80_xmma_fprop_implicit_gemm_tf32f32_tf32f32_f32_nh...         0.00%       0.000us         0.00%       0.000us       0.000us      17.879ms         3.96%      17.879ms     223.488us           0 B           0 B           0 B           0 B            80            --
                                             aten::add_         1.16%       9.682ms         2.14%      17.823ms      22.561us      17.833ms         3.95%      17.833ms      22.574us           0 B           0 B           0 B           0 B           790            --
_ZN7cutlass7Kernel2I52cutlass_80_tensorop_s1688gemm_...         0.00%       0.000us         0.00%       0.000us       0.000us      14.514ms         3.22%      14.514ms     145.145us           0 B           0 B           0 B           0 B           100            --
_Z23implicit_convolve_sgemmIffLi1024ELi5ELi5ELi3ELi3...         0.00%       0.000us         0.00%       0.000us       0.000us      14.313ms         3.17%      14.313ms     715.650us           0 B           0 B           0 B           0 B            20            --
_ZN2at6native29vectorized_elementwise_kernelILi4EZZZ...         0.00%       0.000us         0.00%       0.000us       0.000us      13.168ms         2.92%      13.168ms      13.861us           0 B           0 B           0 B           0 B           950            --
_ZN2at6native29vectorized_elementwise_kernelILi4ENS0...         0.00%       0.000us         0.00%       0.000us       0.000us      13.158ms         2.92%      13.158ms      18.250us           0 B           0 B           0 B           0 B           721            --
_Z26precomputed_convolve_sgemmIfLi1024ELi5ELi5ELi4EL...         0.00%       0.000us         0.00%       0.000us       0.000us      12.754ms         2.83%      12.754ms     637.714us           0 B           0 B           0 B           0 B            20            --
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 833.021ms
Self CUDA time total: 451.052ms


  Run         : fcos_r50—baseline—20260610_002332
  TensorBoard : tensorboard --logdir results\profiler\pytorch\fcos_r50—baseline—20260610_002332
  Perfetto    : ouvrir le .pt.trace.json de results\profiler\pytorch\fcos_r50—baseline—20260610_002332\tensorboard
  Résumés     : results\profiler\pytorch\fcos_r50—baseline—20260610_002332/summary*.txt

───────────────────────────────────────────────────────
  Profiling : efficientdet_d4  [tag=baseline]
───────────────────────────────────────────────────────

==============================================================
  PyTorch Profiler — efficientdet_d4—baseline—20260610_002359
==============================================================
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg       CPU Mem  Self CPU Mem      CUDA Mem  Self CUDA Mem    # of Calls  Total MFLOPs
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                          model_forward         0.00%       0.000us         0.00%       0.000us       0.000us        1.380s       323.24%        1.380s     138.026ms           0 B           0 B           0 B           0 B            10            --
                                          ProfilerStep*         9.39%     145.473ms       100.00%        1.549s     154.877ms       0.000us         0.00%     427.017ms      42.702ms           0 B     -46.88 MB           0 B     -46.88 MB            10            --
                                          model_forward        29.44%     456.023ms        89.57%        1.387s     138.730ms       0.000us         0.00%     422.218ms      42.222ms           0 B           0 B           0 B     -24.60 GB            10            --
                                           aten::conv2d         1.37%      21.188ms        21.74%     336.668ms      89.302us       0.000us         0.00%     228.322ms      60.563us           0 B           0 B       8.11 GB           0 B          3770    426473.244
                                      aten::convolution         1.75%      27.092ms        20.37%     315.480ms      83.682us       0.000us         0.00%     228.322ms      60.563us           0 B           0 B       8.11 GB           0 B          3770            --
                                     aten::_convolution         3.15%      48.822ms        18.62%     288.388ms      76.496us       0.000us         0.00%     228.322ms      60.563us           0 B           0 B       8.11 GB           0 B          3770            --
                                aten::_conv_depthwise2d         1.39%      21.562ms         3.65%      56.480ms      40.928us     114.507ms        26.82%     114.507ms      82.976us           0 B           0 B       3.43 GB           0 B          1380            --
                                aten::cudnn_convolution         5.74%      88.955ms         8.61%     133.347ms      55.794us     101.474ms        23.76%     101.474ms      42.458us           0 B           0 B       4.68 GB       4.68 GB          2390            --
_ZN2at6native51_GLOBAL__N__67b3c33b_18_DepthwiseConv...         0.00%       0.000us         0.00%       0.000us       0.000us      76.517ms        17.92%      76.517ms      63.764us           0 B           0 B           0 B           0 B          1200            --
_ZN7cutlass7Kernel2I51cutlass_80_tensorop_s1688gemm_...         0.00%       0.000us         0.00%       0.000us       0.000us      41.983ms         9.83%      41.983ms     110.483us           0 B           0 B           0 B           0 B           380            --
                                       aten::batch_norm         0.68%      10.542ms        11.06%     171.364ms      86.987us       0.000us         0.00%      41.117ms      20.872us           0 B           0 B       6.46 GB           0 B          1970            --
                           aten::_batch_norm_impl_index         0.92%      14.222ms        10.38%     160.821ms      81.635us       0.000us         0.00%      41.117ms      20.872us           0 B           0 B       6.46 GB           0 B          1970            --
                                 aten::cudnn_batch_norm         4.61%      71.390ms         9.47%     146.599ms      74.416us      41.117ms         9.63%      41.117ms      20.872us           0 B           0 B       6.46 GB           0 B          1970            --
_ZN5cudnn26bn_fw_inf_1C11_kernel_NCHWIffLb1ELi1EEEvT...         0.00%       0.000us         0.00%       0.000us       0.000us      41.117ms         9.63%      41.117ms      20.872us           0 B           0 B           0 B           0 B          1970            --
_ZN2at6native51_GLOBAL__N__67b3c33b_18_DepthwiseConv...         0.00%       0.000us         0.00%       0.000us       0.000us      37.989ms         8.90%      37.989ms     211.051us           0 B           0 B           0 B           0 B           180            --
_ZN2at6native18elementwise_kernelILi128ELi2EZNS0_22g...         0.00%       0.000us         0.00%       0.000us       0.000us      27.939ms         6.54%      27.939ms      15.696us           0 B           0 B           0 B           0 B          1780            --
                                            aten::silu_         1.34%      20.799ms         2.95%      45.659ms      23.905us      22.936ms         5.37%      22.936ms      12.008us           0 B           0 B           0 B           0 B          1910            --

## 12. Profilage feuille par feuille — `profile_model_detailed`

Décomposition du forward pass **module atomique par module atomique** (Conv2d, BatchNorm2d, ReLU, etc.) via des CUDA Events attachés en hooks.

**Principe :**
- `forward_pre_hook` → `start.record()` injecté dans le stream GPU avant chaque feuille
- `forward_hook` → `end.record()` injecté après chaque feuille
- `elapsed_time(start, end)` lu après `synchronize()` = temps GPU réel en ms

**Sortie :** un DataFrame avec une ligne par feuille, trié par `mean_ms` décroissant.

> **Note :** `sum(leaves.mean_ms) ≥ global.mean_ms` car CUDA peut exécuter certains kernels en parallèle. L'écart entre les deux révèle le taux de parallélisme interne du modèle.

In [13]:
from utils.profiler import profile_model_detailed

# ── Choix du modèle à décomposer ──────────────────────────────────────────────
# Changer ici pour analyser un autre modèle
TARGET_MODEL_NAME = "retinanet_r50"
TARGET_MOD        = r50
TARGET_LOAD_FN    = r50.load_model

print(f"Profilage feuille par feuille : {TARGET_MODEL_NAME}")
print(f"  warmup={N_WARMUP} itérations, mesure={N_MEASURE} itérations\n")

model_leaf = TARGET_LOAD_FN(DEVICE)

detailed = profile_model_detailed(
    model         = model_leaf,
    data          = profile_data,
    preprocess_fn = TARGET_MOD.preprocess,
    collate_fn    = TARGET_MOD.collate,
    n_warmup      = N_WARMUP,
    n_measure     = N_MEASURE,
    device        = DEVICE,
)

del model_leaf; torch.cuda.empty_cache()

# ── Résultats globaux ─────────────────────────────────────────────────────────
g = detailed["global"]
print(f"{'─'*55}")
print(f"  Global  : {g['mean_ms']:.2f} ms ± {g['std_ms']:.2f}  ({g['fps']:.1f} FPS)")

df_leaves = detailed["leaves"]
sum_leaves = df_leaves["mean_ms"].sum()
print(f"  Σ feuilles : {sum_leaves:.2f} ms  (parallélisme GPU = {sum_leaves/g['mean_ms']:.2f}x)")
print(f"  Nombre de feuilles actives : {len(df_leaves)}")
print(f"{'─'*55}\n")

# ── Top 20 feuilles les plus coûteuses ────────────────────────────────────────
print("Top 20 feuilles (mean_ms décroissant) :")
display(df_leaves.head(20)[["module", "type", "component", "mean_ms", "std_ms", "pct_sum", "n"]].round(4))

# ── Agrégation par composant ──────────────────────────────────────────────────
print("\nTemps par composant (backbone, fpn, head, …) :")
by_component = (df_leaves.groupby("component")["mean_ms"]
                .sum()
                .sort_values(ascending=False)
                .reset_index())
by_component["pct_total"] = (by_component["mean_ms"] / sum_leaves * 100).round(2)
display(by_component.round(4))

Profilage feuille par feuille : retinanet_r50
  warmup=5 itérations, mesure=10 itérations

───────────────────────────────────────────────────────
  Global  : 77.20 ms ± 12.68  (13.0 FPS)
  Σ feuilles : 27.69 ms  (parallélisme GPU = 0.36x)
  Nombre de feuilles actives : 160
───────────────────────────────────────────────────────

Top 20 feuilles (mean_ms décroissant) :

,module,type,component,mean_ms,std_ms,pct_sum,n
0,backbone.fpn.layer_blocks.0.0,0,backbone,1.3901,0.0210,5.02,10
1,transform,transform,transform,0.9407,0.3945,3.40,10
2,backbone.body.conv1,conv1,backbone,0.9345,0.0710,3.37,10
3,anchor_generator,anchor_generator,anchor_generator,0.7415,0.6247,2.68,10
4,backbone.body.layer4.0.downsample.0,0,backbone,0.6927,0.0507,2.50,10
5,backbone.body.layer2.0.downsample.0,0,backbone,0.6706,0.0225,2.42,10
6,backbone.body.layer3.0.downsample.0,0,backbone,0.6582,0.0471,2.38,10
7,backbone.body.layer4.0.conv2,conv2,backbone,0.6433,0.0514,2.32,10
8,backbone.body.layer4.1.conv2,conv2,backbone,0.5840,0.0806,2.11,10
9,backbone.body.layer4.2.conv2,conv2,backbone,0.5708,0.0376,2.06,10
10,backbone.fpn.extra_blocks.p6,p6,backbone,0.4384,0.0016,1.58,10
11,backbone.body.layer1.0.conv2,conv2,backbone,0.4155,0.0721,1.50,10
12,backbone.body.layer1.1.conv2,conv2,backbone,0.4135,0.0650,1.49,10
13,backbone.body.layer1.2.conv2,conv2,backbone,0.3992,0.0655,1.44,10
14,backbone.body.layer3.3.conv2,conv2,backbone,0.3976,0.0838,1.44,10
15,backbone.body.layer2.0.conv2,conv2,backbone,0.3888,0.0324,1.40,10
16,backbone.body.layer3.0.conv2,conv2,backbone,0.3823,0.0408,1.38,10
17,backbone.body.layer2.3.conv2,conv2,backbone,0.3822,0.0728,1.38,10
18,backbone.body.layer3.2.conv2,conv2,backbone,0.3759,0.0524,1.36,10
19,backbone.body.layer3.4.conv2,conv2,backbone,0.3755,0.0460,1.36,10

Temps par composant (backbone, fpn, head, …) :

          component  mean_ms  pct_total
0          backbone  23.6701      85.48
1              head   2.3385       8.45
2         transform   0.9407       3.40
3  anchor_generator   0.7415       2.68

In [14]:
# ── Décomposition feuille sur tous les modèles ──────────────────────────────
# Cellule optionnelle — peut prendre du temps (6 modèles × N_MEASURE itérations)

MODELS_TO_DETAIL = {
    "retinanet_r50":   (r50,  r50.load_model),
    "retinanet_r101":  (r101, r101.load_model),
    "fcos_r50":        (fcos, fcos.load_model),
    "efficientdet_d4": (ed4,  ed4.load_model),
    "efficientdet_d5": (ed5,  ed5.load_model),
    "efficientdet_d6": (ed6,  ed6.load_model),
}

all_leaves   = {}   # model_name → DataFrame feuilles
all_globals  = {}   # model_name → dict stats global

for mname, (mod, load_fn) in MODELS_TO_DETAIL.items():
    print(f"  {mname}…", end=" ", flush=True)
    m = load_fn(DEVICE)
    res = profile_model_detailed(m, profile_data, mod.preprocess, mod.collate,
                                 n_warmup=N_WARMUP, n_measure=N_MEASURE, device=DEVICE)
    all_leaves[mname]  = res["leaves"]
    all_globals[mname] = res["global"]
    del m; torch.cuda.empty_cache()
    g = res["global"]
    print(f"{g['mean_ms']:.1f} ms  ({g['fps']:.1f} FPS)  — {len(res['leaves'])} feuilles")

# ── Tableau récapitulatif : top-5 feuilles par modèle ─────────────────────────
print("\n\n=== Top 5 feuilles les plus lentes par modèle ===")
for mname, df in all_leaves.items():
    print(f"\n{mname} (global={all_globals[mname]['mean_ms']:.1f} ms):")
    display(df.head(5)[["module", "mean_ms", "pct_sum"]].round(4))

  retinanet_r50… 67.6 ms  (14.8 FPS)  — 160 feuilles
  retinanet_r101…

WARNING:fvcore.common.config:Loading config d:\school\ProjectDSAI2026_2\detectron2\model_zoo\configs\COCO-Detection\../Base-RetinaNet.yaml with yaml.unsafe_load. Your machine may be at risk if the file contains malicious content.
WARNING:fvcore.common.checkpoint:The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std

ValueError: Both events must be recorded before calculating elapsed time.